# docker run --name api-shortifyMe-pg -e POSTGRESQL_USERNAME=docker -e POSTGRESQL_PASSWORD=docker -e POSTGRESQL_DATABASE=api_shortifyMe -p 5432:5432 bitnami/postgresql

version: '3'

services:
  api-shortifyMe-pg:
    image: bitnami/postgresql
    ports:
      - 5432:5432
    environment:
      - POSTGRESQL_USERNAME=docker 
      - POSTGRESQL_PASSWORD=docker 
      - POSTGRESQL_DATABASE=api_shortifyMe